### ISSUE TITLE
setup.py install doesn't download all the requirements

### ISSUE THREAD

**Issue by manalishah** [manalishah/NLTKRest#3]
https://github.com/manalishah/NLTKRest/nltkrest/setup.py

When I use 'python setup.py install' as a command I am overriding the install function since I want to download nltk corpuses as well. But on override it doesn't install the abstract requirements. I have to run 'develop' before that in order to download these requiremnts. I am fairly new to setuptools and couldn't find a way out. It would be great if you could help me fix this.

@chrismattmann

**Comment by chrismattmann** [comment]
@manalishah I'm testing this right now.

**Comment by chrismattmann** [comment]
this is done in #5 please close @manalishah
