### ISSUE TITLE
Follow Guide to pubish nltkrest-examples jar to Sonatype

### ISSUE THREAD

**Issue by chrismattmann** [manalishah/NLTKRest#7]
@manalishah please follow this guide:
http://central.sonatype.org/pages/ossrh-guide.html
1. Publish the nltkrest-examples jar to the Central repo, and set up a profile in the pom.xml so that we can publish it to sonatype.
2. See: http://repo1.maven.org/maven2/edu/usc/ir/ and note that we have already published artifacts there. Please ask @smadha for help.

**Comment by smadha** [comment]
@manalishah if you want an example you can check @ https://github.com/chrismattmann/lucene-geo-gazetteer/blob/8140dd323b67cb58354e76048cabfbe841ed1232/pom.xml

You might want to have a look at 

> [#L90](https://github.com/chrismattmann/lucene-geo-gazetteer/blob/8140dd323b67cb58354e76048cabfbe841ed1232/pom.xml#L90)
> [#L11](https://github.com/chrismattmann/lucene-geo-gazetteer/blob/8140dd323b67cb58354e76048cabfbe841ed1232/pom.xml#L11) - [#L41](https://github.com/chrismattmann/lucene-geo-gazetteer/blob/8140dd323b67cb58354e76048cabfbe841ed1232/pom.xml#L41)

HTH

**Comment by chrismattmann** [comment]
@manalishah do you have any updates here?

**Comment by manalishah** [comment]
@chrismattmann yes, got the access today. will publish it by tonight.

**Comment by chrismattmann** [comment]
great thanks @manalishah

**Comment by chrismattmann** [comment]
issue has been filed: https://issues.sonatype.org/browse/OSSRH-20885 hasn't been published yet though @manalishah

**Comment by chrismattmann** [comment]
PR is opened #9 please merge and then resolve this after publishing.

**Comment by manalishah** [comment]
@chrismattmann  Published to Sonatype:
https://oss.sonatype.org/content/groups/public/edu/usc/ir/nltkrest-examples/
